### ISSUE TITLE
Encrypted status messages

### ISSUE THREAD

**Issue by zagl** [GjjvdBurg/signal2html#17]
Status messages like "You created the group" or "You changed the avatar" appear in the thread but encrypted.

![Encrypted](https://user-images.githubusercontent.com/5967081/116782423-42a0ad80-aa89-11eb-9bf6-88c9fe06beb6.png)

The best solution would be if it was possible to decrypt these messages. But I guess this will not be simple or may even be impossible.

The most simple solution might be to identify such messages and don't output them. 

In my case these messages are always single strings without spaces. I only have similar strings for posted URLs. But these always start with http.

I came up with a very basic test if the message text might be such an encrypted message. I guess there might be better solutions.
    
    def encrypted(text):
        return (
            text is not None
            and text
            and not text.startswith('http')
            and len(text.strip().split()[0]) > 30
        )

**Comment by GjjvdBurg** [comment]
Hi @zagl, thanks for reporting this issue. I know about this problem but it has honestly never really bothered me since it's usually just one message per group if I recall correctly.

Since the decryption doesn't happen here it might be better to see if [signalbackup-tools](https://github.com/bepaald/signalbackup-tools) could fix it. If not, I'd be happy to consider your fix of course

**Comment by zagl** [comment]
I have some longer groups where such messages appear quite often.
I guess it also wouldn't bother me if it didn't break the layout result in an unnecessary horizontal scroll bar.

Another solution would be to style the message <pre> tags with `word-wrap: break-word`.

**Comment by ericthegrey** [comment]
This is not encryption. It's base64 encoding of protobuf messages. I have started some work to make the messages more meaningful (the test to detect these involves some special bits of the _type field).
