### ISSUE TITLE
Print contact name and phone number

### ISSUE THREAD

**Issue by Aztorius** [GjjvdBurg/signal2html#39]
Thank you for this really useful tool !

It would be perfect if the contact name and phone number are displayed at the top of the conversation and also as the folder name.

Thanks.

**Comment by GjjvdBurg** [comment]
Hi @Aztorius, thanks for reporting this. I think the folder name issue has been resolved in version 0.2.4, which I've just released. If you could update signal2html and try again to check that this is the case that would be great. Displaying the contact name in the thread itself is a good idea, so I'll leave this issue open to track that.

**Comment by Aztorius** [comment]
Thank you. I will check for the folder name issue, but it may be caused by a specific version of Signal.
