### ISSUE TITLE
recipient_id is int in db verison 85

### ISSUE THREAD

**Issue by Otto-AA** [GjjvdBurg/signal2html#5]
The model for RecipientId expects `RecipientId._id` to be a string, however an integer value is used. I've only tested it with db version 85, I don't know if this is due to a change in the database schema.

Here is the current thread table which contains the `recipient_ids` column used:

```
sqlite> PRAGMA table_info(thread);
0|_id|INTEGER|0||1
1|date|INTEGER|0|0|0
2|message_count|INTEGER|0|0|0
3|recipient_ids|INTEGER|0||0
4|snippet|TEXT|0||0
5|snippet_cs|INTEGER|0|0|0
6|read|INTEGER|0|1|0
7|type|INTEGER|0|0|0
8|error|INTEGER|0|0|0
9|snippet_type|INTEGER|0|0|0
10|snippet_uri|TEXT|0|NULL|0
11|snippet_content_type|TEXT|0|NULL|0
12|snippet_extras|TEXT|0|NULL|0
13|archived|INTEGER|0|0|0
14|status|INTEGER|0|0|0
15|delivery_receipt_count|INTEGER|0|0|0
16|expires_in|INTEGER|0|0|0
17|last_seen|INTEGER|0|0|0
18|has_sent|INTEGER|0|0|0
19|read_receipt_count|INTEGER|0|0|0
20|unread_count|INTEGER|0|0|0
21|last_scrolled|INTEGER|0|0|0
22|pinned|INTEGER|0|0|0
```

Because of this I had to comment out this line to make it work for groups: https://github.com/GjjvdBurg/signal2html/blob/b5d4dbecc8972bd9659563d91c693e1956a2ba20/signal2html/html.py#L71

**Comment by GjjvdBurg** [comment]
Hi @Otto-AA, thanks for reporting this and apologies for the slow response. I think I've fixed it now in master, and I'll prepare a release soon. If it's not too much trouble it would be great if you could confirm whether the update works (if it does, I can add version 85 to the list of tested versions). Thanks!
