### ISSUE TITLE
error parsing command line unknown option

### ISSUE THREAD

**Issue by pushkar132** [GjjvdBurg/signal2html#66]
![WhatsApp Image 2022-04-24 at 5 07 04 PM](https://user-images.githubusercontent.com/77731859/164974597-3e2cceb7-12c9-467c-bf42-afe960814ea0.jpeg)

I have been using latest version of signal2html tool with ubuntu but whenever I try to extract my backup files , I get an error called " error parsing command line option". I never came across this type of error before also I have tried to extract my other backup files too but every time the same error is displayed , If anyone knows about this issue then please give a solution about it ASAP! .

**Comment by GjjvdBurg** [comment]
This is the repository for signal2html. Your screenshot suggests you're trying to use signalbackup-tools, which is here: https://github.com/bepaald/signalbackup-tools
