### ISSUE TITLE
Relative URLs to attachments

### ISSUE THREAD

**Issue by th1l6f** [GjjvdBurg/signal2html#7]
First: thank you very much for creating this project! It's a very nice solution to preserve messages.

I was surprised about the absolute paths to attachments in the generated html. I moved the generated documents, which broke all references. All attachments get copied to a certain place. So, it would be easy to switch to relative urls. It seems like the logic is perfectly localized in get_attachment_filename(…). Just returning ```"attachments/"+fname``` should do the job.

BTW: You’re creating paths using OS-dependent delimiters. I guess, in HTML it is preferable to use forward-slashes.

**Comment by GjjvdBurg** [comment]
Thanks for reporting this issue @th1l6f! I've just fixed this and will update the package on PyPI asap.
